CREATE TABLE `catalogue` (
  `PRODUIT_POCLEUNIK` integer UNIQUE,
  `PRODUIT_REF` varchar(255) PRIMARY KEY,
  `REFCIALE_ARCLEUNIK` integer UNIQUE,
  `REFCIALE_REFART` varchar(255),
  `REFCIALE_REFCAT` varchar(255),
  `POTRAD_DESI` varchar(255),
  `REFCIALE_CTVA` integer,
  `FICTECH_MEMOCAT` varchar(255),
  `FICTECH_MEMONET` varchar(255),
  `PRODUIT_MARQUE` varchar(255),
  `PRODUIT_CLEP01` varchar(255),
  `PRODUIT_CLEP02` varchar(255),
  `PRODUIT_CLEP03` varchar(255),
  `PRODUIT_CLEP04` varchar(255),
  `PRODUIT_CLEP06` varchar(255),
  `PRODUIT_CLEP07` varchar(255),
  `PRODUIT_GCOLORIS` varchar(255),
  `PRODUIT_GTAILLE` varchar(255),
  `PRODUIT_CLEP12` varchar(255),
  `REFCIALE_FICHEINA` varchar(255),
  `REFCIALE_MODTE` integer,
  `PRODUIT_MODTE` integer,
  `ARTICLE_POIDS` varchar(255),
  `ARTICLE_HNORMEL` integer,
  `ARTICLE_CATEG` integer
);
